<?php
include 'config.php';
header('Content-Type: application/json');
error_reporting(0);
ini_set('display_errors', 0);

if (!isset($_SESSION['user_id'])) {
    http_response_code(401);
    echo json_encode(["error" => "Unauthorized"]);
    exit();
}

$user_id = $_SESSION['user_id'];

// Verify Agent Role
$stmt = $pdo->prepare("SELECT role, referral_code, name, email, bank_account_number, bank_ifsc_code, bank_holder_name, usdt_address FROM users WHERE id = ?");
$stmt->execute([$user_id]);
$user = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$user || $user['role'] !== 'agent') {
    http_response_code(403);
    echo json_encode(["error" => "Access Denied: Agents Only"]);
    exit();
}

/**
 * Helper to get User Stats (Total Deposit)
 */
function getUserDeposit($pdo, $uid) {
    $stmt = $pdo->prepare("SELECT SUM(amount) FROM deposits WHERE user_id = ? AND status = 'success'");
    $stmt->execute([$uid]);
    return $stmt->fetchColumn() ?: 0;
}

/**
 * Helper to get Commission Generated by a Specific User for the Agent
 */
function getCommissionFromUser($pdo, $agent_id, $from_uid) {
    $stmt = $pdo->prepare("SELECT SUM(amount) FROM agent_commissions WHERE agent_id = ? AND from_user_id = ?");
    $stmt->execute([$agent_id, $from_uid]);
    return $stmt->fetchColumn() ?: 0;
}

// 1. Total Global Earnings
$stmt = $pdo->prepare("SELECT SUM(amount) FROM agent_commissions WHERE agent_id = ?");
$stmt->execute([$user_id]);
$total_earnings = $stmt->fetchColumn() ?: 0;

// 2. Recent Commissions
$stmt = $pdo->prepare("
    SELECT ac.*, u.name as from_user_name, u.email as from_user_email 
    FROM agent_commissions ac 
    JOIN users u ON ac.from_user_id = u.id 
    WHERE ac.agent_id = ? 
    ORDER BY ac.created_at DESC 
    LIMIT 50
");
$stmt->execute([$user_id]);
$commissions = $stmt->fetchAll(PDO::FETCH_ASSOC);

// 3. Network Stats & Tree Building
$stats = [
    'level1' => ['count' => 0, 'deposit' => 0, 'commission' => 0],
    'level2' => ['count' => 0, 'deposit' => 0, 'commission' => 0],
    'level3' => ['count' => 0, 'deposit' => 0, 'commission' => 0]
];

$team_list = [];

// --- Level 1 ---
$stmt = $pdo->prepare("SELECT id, name, email, created_at, referral_code FROM users WHERE referred_by = ?");
$stmt->execute([$user['referral_code']]);
$level1_users = $stmt->fetchAll(PDO::FETCH_ASSOC);

foreach ($level1_users as $l1) {
    // Stats for L1 User
    $dep = getUserDeposit($pdo, $l1['id']);
    $com = getCommissionFromUser($pdo, $user_id, $l1['id']);
    
    // Aggregates
    $stats['level1']['count']++;
    $stats['level1']['deposit'] += $dep;
    $stats['level1']['commission'] += $com;
    
    // Add to Team List
    $team_list[] = [
        'id' => $l1['id'],
        'name' => $l1['name'],
        'email' => $l1['email'],
        'level' => 1,
        'join_date' => $l1['created_at'],
        'total_deposit' => $dep,
        'earned_from' => $com,
        'referrer' => 'You'
    ];
    
    // --- Level 2 ---
    if ($l1['referral_code']) {
        $stmt = $pdo->prepare("SELECT id, name, email, created_at, referral_code FROM users WHERE referred_by = ?");
        $stmt->execute([$l1['referral_code']]);
        $level2_users = $stmt->fetchAll(PDO::FETCH_ASSOC);
        
        foreach ($level2_users as $l2) {
             // Stats for L2 User
            $dep2 = getUserDeposit($pdo, $l2['id']);
            $com2 = getCommissionFromUser($pdo, $user_id, $l2['id']);

            // Aggregates
            $stats['level2']['count']++;
            $stats['level2']['deposit'] += $dep2;
            $stats['level2']['commission'] += $com2;
            
            // Add to Team List
            $team_list[] = [
                'id' => $l2['id'],
                'name' => $l2['name'],
                'email' => $l2['email'],
                'level' => 2,
                'join_date' => $l2['created_at'],
                'total_deposit' => $dep2,
                'earned_from' => $com2,
                'referrer' => $l1['name']
            ];
            
            // --- Level 3 ---
            if ($l2['referral_code']) {
                $stmt = $pdo->prepare("SELECT id, name, email, created_at FROM users WHERE referred_by = ?");
                $stmt->execute([$l2['referral_code']]);
                $level3_users = $stmt->fetchAll(PDO::FETCH_ASSOC);
                
                foreach ($level3_users as $l3) {
                     // Stats for L3 User
                    $dep3 = getUserDeposit($pdo, $l3['id']);
                    $com3 = getCommissionFromUser($pdo, $user_id, $l3['id']);
        
                    // Aggregates
                    $stats['level3']['count']++;
                    $stats['level3']['deposit'] += $dep3;
                    $stats['level3']['commission'] += $com3;

                    // Add to Team List
                    $team_list[] = [
                        'id' => $l3['id'],
                        'name' => $l3['name'],
                        'email' => $l3['email'],
                        'level' => 3,
                        'join_date' => $l3['created_at'],
                        'total_deposit' => $dep3,
                        'earned_from' => $com3,
                        'referrer' => $l2['name']
                    ];
                }
            }
        }
    }
}

echo json_encode([
    "success" => true,
    "agent_data" => [
        "name" => $user['name'],
        "email" => $user['email'],
        "referral_code" => $user['referral_code'],
        // Bank Details for Pre-fill
        "bank_account_number" => $user['bank_account_number'],
        "bank_ifsc_code" => $user['bank_ifsc_code'],
        "bank_holder_name" => $user['bank_holder_name'],
        "usdt_address" => $user['usdt_address'],
        
        "total_earnings" => $total_earnings,
        "commissions" => $commissions,
        "stats" => $stats,
        "team_list" => $team_list
    ]
]);
?>
