<?php
include 'config.php';
header('Content-Type: application/json');
error_reporting(0);
ini_set('display_errors', 0);

if (!isset($_SESSION['user_id'])) {
    http_response_code(401);
    echo json_encode(["error" => "Unauthorized"]);
    exit();
}

$user_id = $_SESSION['user_id'];

// Verify Agent Role
$stmt = $pdo->prepare("SELECT role, referral_code, name, email, bank_account_number, bank_ifsc_code, bank_holder_name, usdt_address, telegram_link FROM users WHERE id = ?");
$stmt->execute([$user_id]);
$user = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$user || $user['role'] !== 'agent') {
    http_response_code(403);
    echo json_encode(["error" => "Access Denied: Agents Only"]);
    exit();
}

/**
 * Helper to get User Stats (Total Deposit)
 */
function getUserDeposit($pdo, $uid) {
    $stmt = $pdo->prepare("SELECT SUM(amount) FROM deposits WHERE user_id = ? AND status = 'success'");
    $stmt->execute([$uid]);
    return $stmt->fetchColumn() ?: 0;
}

/**
 * Helper to get Commission Generated by a Specific User for the Agent
 */
function getCommissionFromUser($pdo, $agent_id, $from_uid, $has_status = true, $amount_field = "amount") {
    $status_condition = $has_status ? "AND status = 'approved'" : "";
    $stmt = $pdo->prepare("SELECT SUM($amount_field) FROM agent_commissions WHERE agent_id = ? AND from_user_id = ? $status_condition");
    $stmt->execute([$agent_id, $from_uid]);
    return $stmt->fetchColumn() ?: 0;
}

/**
 * Helper to get today's deposit count for a user
 */
function getTodayDepositCount($pdo, $uid) {
    $stmt = $pdo->prepare("SELECT COUNT(*) FROM deposits WHERE user_id = ? AND status = 'success' AND DATE(created_at) = CURDATE()");
    $stmt->execute([$uid]);
    return $stmt->fetchColumn() ?: 0;
}

/**
 * Helper to get today's deposit amount for a user
 */
function getTodayDepositAmount($pdo, $uid) {
    $stmt = $pdo->prepare("SELECT SUM(amount) FROM deposits WHERE user_id = ? AND status = 'success' AND DATE(created_at) = CURDATE()");
    $stmt->execute([$uid]);
    return $stmt->fetchColumn() ?: 0;
}

/**
 * Helper to check if user made first deposit today
 */
function isFirstDepositToday($pdo, $uid) {
    // Check if this is their first ever deposit
    $stmt = $pdo->prepare("SELECT COUNT(*) FROM deposits WHERE user_id = ? AND status = 'success'");
    $stmt->execute([$uid]);
    $total_deposits = $stmt->fetchColumn();
    
    if ($total_deposits == 1) {
        // Check if that one deposit was today
        $stmt = $pdo->prepare("SELECT COUNT(*) FROM deposits WHERE user_id = ? AND status = 'success' AND DATE(created_at) = CURDATE()");
        $stmt->execute([$uid]);
        return $stmt->fetchColumn() > 0;
    }
    return false;
}

// Get time period from request (default: today)
$period = $_GET['period'] ?? 'today';
$date_filter = '';
$date_params = [];

switch($period) {
    case 'week':
        $date_filter = "AND created_at >= DATE_SUB(CURDATE(), INTERVAL 7 DAY)";
        break;
    case 'month':
        $date_filter = "AND created_at >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)";
        break;
    case 'all':
        $date_filter = "";
        break;
    case 'today':
    default:
        $date_filter = "AND DATE(created_at) = CURDATE()";
        break;
}

// Check if status column exists in agent_commissions table
try {
    $stmt = $pdo->query("SHOW COLUMNS FROM agent_commissions LIKE 'status'");
    $has_status = $stmt->rowCount() > 0;
} catch (Exception $e) {
    $has_status = false;
}

// Check if adjusted_amount column exists
try {
    $stmt = $pdo->query("SHOW COLUMNS FROM agent_commissions LIKE 'adjusted_amount'");
    $has_adjusted_amount = $stmt->rowCount() > 0;
} catch (Exception $e) {
    $has_adjusted_amount = false;
}

// Use COALESCE only if adjusted_amount exists, otherwise just use amount
$amount_field = $has_adjusted_amount ? "COALESCE(adjusted_amount, amount)" : "amount";

// 1. Total Global Earnings (only approved commissions)
$status_condition = $has_status ? "AND status = 'approved'" : "";
$stmt = $pdo->prepare("SELECT SUM($amount_field) FROM agent_commissions WHERE agent_id = ? $status_condition");
$stmt->execute([$user_id]);
$total_earnings = $stmt->fetchColumn() ?: 0;

// Pending Commissions (not yet approved)
$pending_earnings = 0;
if ($has_status) {
    $stmt = $pdo->prepare("SELECT SUM($amount_field) FROM agent_commissions WHERE agent_id = ? AND status = 'pending'");
    $stmt->execute([$user_id]);
    $pending_earnings = $stmt->fetchColumn() ?: 0;
}

// Total Withdrawn
$stmt = $pdo->prepare("SELECT SUM(amount) FROM withdraws WHERE user_id = ? AND status = 'approved'");
$stmt->execute([$user_id]);
$total_withdrawn = $stmt->fetchColumn() ?: 0;

// Available Balance = Total Earnings - Total Withdrawn
$available_balance = $total_earnings - $total_withdrawn;

// Period-wise Commission
$period_status_condition = $has_status ? "AND status = 'approved'" : "";
$stmt = $pdo->prepare("SELECT SUM($amount_field) FROM agent_commissions WHERE agent_id = ? $period_status_condition $date_filter");
$stmt->execute([$user_id]);
$period_commission = $stmt->fetchColumn() ?: 0;

// Today's Total Commission (for display)
$stmt = $pdo->prepare("SELECT SUM($amount_field) FROM agent_commissions WHERE agent_id = ? $period_status_condition AND DATE(created_at) = CURDATE()");
$stmt->execute([$user_id]);
$today_commission = $stmt->fetchColumn() ?: 0;

// 2. Commissions with filters
// Note: Commission history shows all commissions by default (not filtered by period)
// Period filter only affects the summary commission amount
$status_filter = $_GET['status'] ?? 'all';
$level_filter = $_GET['level'] ?? 'all';
$search_query = $_GET['search'] ?? '';

$where_conditions = ["ac.agent_id = ?"];
$params = [$user_id];

// Status filter (only if status column exists)
if ($status_filter !== 'all') {
    if ($has_status) {
        $where_conditions[] = "ac.status = ?";
        $params[] = $status_filter;
    }
    // If status column doesn't exist and filter is not 'all', we can't filter by status
    // All records will be shown (backward compatibility)
}

// Level filter
if ($level_filter !== 'all' && is_numeric($level_filter)) {
    $where_conditions[] = "ac.level = ?";
    $params[] = $level_filter;
}

// Date range filter (overrides period filter if provided)
$date_from = $_GET['date_from'] ?? '';
$date_to = $_GET['date_to'] ?? '';

// Commission history shows ALL commissions by default
// Period filter only affects the summary commission amount, not the history list
if ($date_from || $date_to) {
    // Remove period filter if date range is provided
    $where_conditions = array_values(array_filter($where_conditions, function($condition) {
        return !preg_match('/created_at.*CURDATE|created_at.*DATE_SUB/', $condition);
    }));
    
    if ($date_from && $date_to) {
        $where_conditions[] = "DATE(ac.created_at) >= ? AND DATE(ac.created_at) <= ?";
        $params[] = $date_from;
        $params[] = $date_to;
    } elseif ($date_from) {
        $where_conditions[] = "DATE(ac.created_at) >= ?";
        $params[] = $date_from;
    } elseif ($date_to) {
        $where_conditions[] = "DATE(ac.created_at) <= ?";
        $params[] = $date_to;
    }
}

// Search filter
if ($search_query) {
    $where_conditions[] = "(u.name LIKE ? OR u.email LIKE ?)";
    $search_param = "%$search_query%";
    $params[] = $search_param;
    $params[] = $search_param;
}

// Ensure we have at least one condition
if (empty($where_conditions)) {
    $where_conditions = ["ac.agent_id = ?"];
    $params = [$user_id];
}

$where_clause = implode(" AND ", $where_conditions);

try {
    $stmt = $pdo->prepare("
        SELECT ac.*, u.name as from_user_name, u.email as from_user_email 
        FROM agent_commissions ac 
        JOIN users u ON ac.from_user_id = u.id 
        WHERE $where_clause
        ORDER BY ac.created_at DESC 
        LIMIT 100
    ");
    $stmt->execute($params);
    $commissions = $stmt->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    // Log error but don't break the response
    error_log("Agent stats commission query error: " . $e->getMessage() . " | WHERE: $where_clause");
    $commissions = [];
}

// 3. Network Stats & Tree Building
$stats = [
    'level1' => ['count' => 0, 'deposit' => 0, 'commission' => 0],
    'level2' => ['count' => 0, 'deposit' => 0, 'commission' => 0],
    'level3' => ['count' => 0, 'deposit' => 0, 'commission' => 0]
];

// Direct and Team Subordinates Stats (for today)
$direct_subordinates = [
    'number_of_register' => 0,
    'deposit_number' => 0,
    'deposit_amount' => 0,
    'first_deposit_count' => 0
];

$team_subordinates = [
    'number_of_register' => 0,
    'deposit_number' => 0,
    'deposit_amount' => 0,
    'first_deposit_count' => 0
];

$team_list = [];

// --- Level 1 ---
$stmt = $pdo->prepare("SELECT id, name, email, created_at, referral_code FROM users WHERE referred_by = ?");
$stmt->execute([$user['referral_code']]);
$level1_users = $stmt->fetchAll(PDO::FETCH_ASSOC);

foreach ($level1_users as $l1) {
    // Stats for L1 User
    $dep = getUserDeposit($pdo, $l1['id']);
    $com = getCommissionFromUser($pdo, $user_id, $l1['id'], $has_status, $amount_field);
    
    // Today's stats for Direct Subordinates
    $today_dep_count = getTodayDepositCount($pdo, $l1['id']);
    $today_dep_amount = getTodayDepositAmount($pdo, $l1['id']);
    $is_first_today = isFirstDepositToday($pdo, $l1['id']);
    
    // Aggregates
    $stats['level1']['count']++;
    $stats['level1']['deposit'] += $dep;
    $stats['level1']['commission'] += $com;
    
    // Direct Subordinates Today Stats
    $direct_subordinates['number_of_register']++;
    $direct_subordinates['deposit_number'] += $today_dep_count;
    $direct_subordinates['deposit_amount'] += $today_dep_amount;
    if ($is_first_today) {
        $direct_subordinates['first_deposit_count']++;
    }
    
    // Add to Team List
    $team_list[] = [
        'id' => $l1['id'],
        'name' => $l1['name'],
        'email' => $l1['email'],
        'level' => 1,
        'join_date' => $l1['created_at'],
        'total_deposit' => $dep,
        'earned_from' => $com,
        'referrer' => 'You'
    ];
    
    // --- Level 2 ---
    if ($l1['referral_code']) {
        $stmt = $pdo->prepare("SELECT id, name, email, created_at, referral_code FROM users WHERE referred_by = ?");
        $stmt->execute([$l1['referral_code']]);
        $level2_users = $stmt->fetchAll(PDO::FETCH_ASSOC);
        
        foreach ($level2_users as $l2) {
             // Stats for L2 User
            $dep2 = getUserDeposit($pdo, $l2['id']);
            $com2 = getCommissionFromUser($pdo, $user_id, $l2['id'], $has_status, $amount_field);

            // Today's stats for Team Subordinates (Level 2)
            $today_dep_count2 = getTodayDepositCount($pdo, $l2['id']);
            $today_dep_amount2 = getTodayDepositAmount($pdo, $l2['id']);
            $is_first_today2 = isFirstDepositToday($pdo, $l2['id']);

            // Aggregates
            $stats['level2']['count']++;
            $stats['level2']['deposit'] += $dep2;
            $stats['level2']['commission'] += $com2;
            
            // Team Subordinates Today Stats (Level 2)
            $team_subordinates['number_of_register']++;
            $team_subordinates['deposit_number'] += $today_dep_count2;
            $team_subordinates['deposit_amount'] += $today_dep_amount2;
            if ($is_first_today2) {
                $team_subordinates['first_deposit_count']++;
            }
            
            // Add to Team List
            $team_list[] = [
                'id' => $l2['id'],
                'name' => $l2['name'],
                'email' => $l2['email'],
                'level' => 2,
                'join_date' => $l2['created_at'],
                'total_deposit' => $dep2,
                'earned_from' => $com2,
                'referrer' => $l1['name']
            ];
            
            // --- Level 3 ---
            if ($l2['referral_code']) {
                $stmt = $pdo->prepare("SELECT id, name, email, created_at FROM users WHERE referred_by = ?");
                $stmt->execute([$l2['referral_code']]);
                $level3_users = $stmt->fetchAll(PDO::FETCH_ASSOC);
                
                foreach ($level3_users as $l3) {
                     // Stats for L3 User
                    $dep3 = getUserDeposit($pdo, $l3['id']);
                    $com3 = getCommissionFromUser($pdo, $user_id, $l3['id'], $has_status, $amount_field);
        
                    // Today's stats for Team Subordinates (Level 3)
                    $today_dep_count3 = getTodayDepositCount($pdo, $l3['id']);
                    $today_dep_amount3 = getTodayDepositAmount($pdo, $l3['id']);
                    $is_first_today3 = isFirstDepositToday($pdo, $l3['id']);
        
                    // Aggregates
                    $stats['level3']['count']++;
                    $stats['level3']['deposit'] += $dep3;
                    $stats['level3']['commission'] += $com3;
                    
                    // Team Subordinates Today Stats (Level 3)
                    $team_subordinates['number_of_register']++;
                    $team_subordinates['deposit_number'] += $today_dep_count3;
                    $team_subordinates['deposit_amount'] += $today_dep_amount3;
                    if ($is_first_today3) {
                        $team_subordinates['first_deposit_count']++;
                    }

                    // Add to Team List
                    $team_list[] = [
                        'id' => $l3['id'],
                        'name' => $l3['name'],
                        'email' => $l3['email'],
                        'level' => 3,
                        'join_date' => $l3['created_at'],
                        'total_deposit' => $dep3,
                        'earned_from' => $com3,
                        'referrer' => $l2['name']
                    ];
                }
            }
        }
    }
}

try {
    $response = [
        "success" => true,
        "agent_data" => [
            "name" => $user['name'],
            "email" => $user['email'],
            "referral_code" => $user['referral_code'],
            // Bank Details for Pre-fill
            "bank_account_number" => $user['bank_account_number'],
            "bank_ifsc_code" => $user['bank_ifsc_code'],
            "bank_holder_name" => $user['bank_holder_name'],
            "usdt_address" => $user['usdt_address'],
            "telegram_link" => $user['telegram_link'],
            
            "total_earnings" => $total_earnings,
            "pending_earnings" => $pending_earnings,
            "total_withdrawn" => $total_withdrawn,
            "available_balance" => $available_balance,
            "today_commission" => $today_commission,
            "period_commission" => $period_commission,
            "period" => $period,
            "commissions" => $commissions,
            "stats" => $stats,
            "direct_subordinates" => $direct_subordinates,
            "team_subordinates" => $team_subordinates,
            "team_list" => $team_list
        ]
    ];
    echo json_encode($response);
} catch (Exception $e) {
    http_response_code(500);
    echo json_encode([
        "success" => false,
        "error" => "Internal server error",
        "message" => $e->getMessage()
    ]);
    error_log("Agent stats error: " . $e->getMessage());
}
?>
